### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by wedahafiz** [eshaqfahimi/DMIS#8]

**Comment by wedahafiz** [comment]
dear eshaq i cant  see the tasks you are done with so please dont make them archive .
when you reopen a task please change its label too .
and thank you for updating your tasks status

**Comment by eshaqfahimi** [comment]
Hi, Dear, Teacher;
I don't see my tasks which I finished theme.

**Comment by wedahafiz** [comment]
yeah thats  because u have archived them dont click archive please just close tasks
